### ISSUE TITLE
STANFORD : No Results Found of employee on timecard

### ISSUE THREAD

**Issue by eyuapptree** [apptreesoftware/revolution#91] opened 2016-10-18 03:14 UTC
AppID : lbreuat.stanford.edu
Build Version : 5.4.3-2151

Login as KJHCHANG 
Go to "Timecard" from menu item
Tap on  "Choose Employee" under the calendar
It display No Results Found error

Mellissa delete the list on S3, still same problem

I try another user XJAH011 it display same error
 
This is not happen on any other environment

The server site log (at_log) says, list/timeentrymember never never been called

I tested with local connector, the call is fine and I can get result for KJHCHANG

Mellissa set the cache level to 2 minutes, and I point to my local connector, it never try to get list from connector

**Comment by matthewtsmith** [comment] 2016-10-18 15:33
@alexisandreason I think this is a bug the new core has with "authenticated" lists. Please investigate.

**Comment by matthewtsmith** [comment] 2016-10-18 19:51
I believe the $username is not getting included in the listCacheKey. The client then does not substitute in the username when checking S3.

**Comment by mellissatort** [comment] 2016-10-18 23:11
Worked with Stanford AS to restart UAT.  Updated LBREUAT connector url.  Tested list display and worked successfully.  Will continue to monitor, but will close this ticket as the issue is resolved currently.

**Closed by mellissatort** 2016-10-18 23:11 UTC
Labels: Core, CRITICAL, iOS
