### ISSUE TITLE
Web: Create New User Store List is slow to display list and filter list

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#152] opened 2016-11-02 23:08 UTC
Create new user account
Select Store attribute
List takes a while to display the list.
Type "Carnival" and list takes a while to filter

service.taylorfreezer.net
sandbox / beta

**Comment by mellissatort** [comment] 2016-11-02 23:16
To expand upon the behavior when I click on the Store No list the refresh circle icon spins for a while and then stops like its stuck for many seconds and then finally displays the list.

When I type "carnival" I'm able to type the entire word and wait about 8 seconds for the list to finally filter.

**Comment by johnpryan** [comment] 2016-11-03 14:35
I'm having some difficulty reproducing this.  What device are you using?

**Comment by mellissatort** [comment] 2016-11-03 14:49
@johnpryan I am testing it with iPhone 6 (iOS 10).

**Comment by johnpryan** [comment] 2016-11-03 17:18
This is a legitimate issue - The app uses an out of date (slow) mechanism to interoperate with the AWS SDK javascript code

**Comment by mellissatort** [comment] 2016-11-03 20:32
@johnpryan I feel this is a critical issue to resolve before production deployment as the user experience with this is not good.  The list is slow to return, filter, clear filter, etc.  I'm going to update this to Critical

**Comment by johnpryan** [comment] 2016-11-03 20:38
This PR will help: https://github.com/apptreesoftware/apptreerevolution-web/pull/68 but it doesn't eliminate the need to execute a SQL query.

Matt and I were also considering using a server list; since that would also avoid running a SQLite query client-side

Here's what I'm seeing:

| platform      | load app | load list | filter list |   |
|---------------|----------|-----------|-------------|---|
| mobile safari | 6s       | 2s        | 4s          |   |
|               |          |           |             |   |
|               |          |           |             |   |

**Comment by johnpryan** [comment] 2016-11-03 23:57
FYI @mellissatort Matt is going to add indexes to the SQLite databases.  This improves filtering from 200ms down to 50ms (4x speedup) in Chrome.  On iOS this feels much faster too.  

The slowest part is still loading the list (I'm actually seeing this take about 6s on iOS)

**Comment by matthewtsmith** [comment] 2016-11-04 17:19
@johnpryan deployed, please test

**Comment by johnpryan** [comment] 2016-11-04 17:35
filtering is working on average 60-80ms on Chrome (down from 200ms)

**Comment by johnpryan** [comment] 2016-11-04 17:40
@mellissatort I feel we've made some good improvements; loading the app and the list are only slightly faster, (still ~6s each) but filtering is a much better experience.

**Comment by mellissatort** [comment] 2016-11-04 19:42
@johnpryan loading the registration form took 7 seconds.  When I clicked on the Store No field it took 32 seconds for the list to display.  Filtering the list is much better and filters almost at the time I'm typing characters.  Is there any way to speed up the Store No list display of 32 seconds?  This was tested on iOS

**Comment by johnpryan** [comment] 2016-11-04 19:50
We could load the form more quickly if we decide to render it before all of the lists are on S3.  

How often does loading the list take 32 seconds?  I'm seeing it take ~5-6 seconds on average (on iOS)

**Comment by johnpryan** [comment] 2016-11-04 23:21
This should be faster now that it's a search list.  The reality is that this is a large list and won't always be fast on the web client, especially on mobile.

I'm open to having a separate discussion or ticket about mobile performance but I'm going to close this issue since the critical aspects have been (somewhat) resolved.

**Closed by johnpryan** 2016-11-04 23:21 UTC
Labels: CRITICAL, Web Client
