### ISSUE TITLE
Losing Pusher Connection when Switching App ID

### ISSUE THREAD

**Issue by RobertGuinn** [apptreesoftware/revolution#145] opened 2016-10-31 21:11 UTC
**Description**

Was logged into Taylor Freezer.
Swtich app from Taylor Login Screen to 'demo.rice.edu'
Login as jlw8
Workbenches don't load.  Get 'syncing data' message at bottom.

Matt stated this was because of pusher issue.

**Steps to Reproduce**

**App ID**

demo.rice.edu

**Version Number**

5.4.4 (2228) iOS

**Comment by matthewtsmith** [comment] 2016-11-01 13:04
I believe this is a duplicate of https://github.com/apptreesoftware/revolution/issues/119

**Closed** 2016-11-02 22:32 UTC
