### ISSUE TITLE
Web/Portal:  User Registration page from link in portal does not look like "Create Account" used on client

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#160] opened 2016-11-03 17:56 UTC
In Portal when I select the "User Registration" page link on the builder the configured registration form does not look like the form that displays when a user selects the Create Account link on the Taylor Freezer login page.

http://sandbox.apptreesoftware.com/#/app/service.taylorfreezer.net/beta/builder/device/page/registration

How do I edit the user registration page for the Create Account link in Taylor Freezer?

App ID:  service.taylorfreezer.net
sandbox / beta

**Comment by johnpryan** [comment] 2016-11-03 19:02
Can you confirm that the configuration is saving properly by refreshing the Portal browser window? 

I can reproduce, but it's only because the portal isn't saving the configuration.

**Comment by mellissatort** [comment] 2016-11-03 19:05
@johnpryan I selected the User Registration page in the portal which took me to http://sandbox.apptreesoftware.com/#/app/service.taylorfreezer.net/beta/builder/device/page/registration.  If I do a browser refresh on this page it still is not displaying the right form config

**Comment by johnpryan** [comment] 2016-11-03 19:06
As per the slack conversation, this looks like a portal issue; reassigning to @sambbaron

**Comment by johnpryan** [comment] 2016-11-03 19:10
steps to reproduce:
1. make a change to http://sandbox.apptreesoftware.com/#/app/service.taylorfreezer.net/beta/builder/device/page/registration
2. save
3. refresh the browser
4. observe the changes were not applied

**Comment by sambbaron** [comment] 2016-11-03 19:38
Fix deployed to portal sandbox `0.8.0-dev.36.8`

**Comment by mellissatort** [comment] 2016-11-03 20:03
@sambbaron Confirmed the forms now look the same.  I updated the user registration configuration hiding the Customer No field and saw the config update on the user registration form.

**Closed** 2016-11-03 20:19 UTC
Labels: CRITICAL, Portal, Web Client
