### ISSUE TITLE
App Users not loading

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/revolution#110] opened 2016-10-19 21:20 UTC
http://sandbox.apptreesoftware.com/#/app/inspect.corrigo.com/app-users

Sandbox - inspect.corrigo.com

I tap on App Users and an exception gets logged in the console. Screen stays blank

**Comment by sambbaron** [comment] 2016-10-19 21:34
@matthewtsmith @alexisandreason The problem is that `additionalUserInfo` is being returned as a dictionary (empty in this case) instead of an array.  I am expecting `additionalUserInfo` to be an array of custom user attributes that includes a `value` property.

I will make the fix so this doesn't cause an exception.  I am assigning this issue to Alexis.

**Closed** 2016-10-19 22:16 UTC
Labels: bug, Core, CRITICAL
