### ISSUE TITLE
STANFORD : Some work order number get truncated in wo lov

### ISSUE THREAD

**Issue by eyuapptree** [apptreesoftware/revolution#10] opened 2016-09-30 02:06 UTC
appID : somint.stanford.edu
AppVersion : 5.4.3-2173

1. logged in as violanti, 
2. Select Timecard on the left nav, 
3. select the + sign on the top, 
4, select the WO number field, 
5) when LOV items display, you will notice some wo number is truncated, see attachment
![ed651](https://cloud.githubusercontent.com/assets/22424216/18978397/69265624-86f5-11e6-9fab-81ef8c4e48a3.PNG)

**Comment by matthewtsmith** [comment] 2016-09-30 12:41
@eyuapptree This template is not meant to have a long text in the top right side. It's meant for something small like a status. I suggest you swap the `description` label and the `operation number`.

**Comment by mellissatort** [comment] 2016-09-30 13:23
@matthewtsmith I have swapped the OPERATION SEQ and RESOURCE CODE fields in the list display format as well as on the WO attribute field on the form.  When I view the list on device (iOS or Android) the changes I made are not being reflected.  I have logged out of the app back to the app Id entry screen and logged back in but no change.

**Comment by matthewtsmith** [comment] 2016-09-30 13:26
@mellissatort did the application show a config update?

**Comment by mellissatort** [comment] 2016-09-30 13:28
@matthewtsmith yes it did, but still the list format did not change after re-logging in.

**Comment by matthewtsmith** [comment] 2016-09-30 13:30
@mellissatort are there any spaces on the template that are not filled out? What template are you using?

**Comment by mellissatort** [comment] 2016-09-30 13:32
Card Layout 7 Attributes + Color Stripe.  The only field on the template not filled out is the Badge which is not relevant for this list display.

<img width="899" alt="screen shot 2016-09-30 at 9 30 53 am" src="https://cloud.githubusercontent.com/assets/22403044/18993330/a63874d4-86f0-11e6-9522-ebf6eeba97a3.png">

**Comment by matthewtsmith** [comment] 2016-09-30 13:34
@mellissatort Does this happen on Android or is it only iOS. I think this may be a problem with how we are reading in templates but if it only happens on iOS it could just be an issue with that template on iOS.

**Comment by mellissatort** [comment] 2016-09-30 13:36
@matthewtsmith it is happening on both android and iOS

**Comment by matthewtsmith** [comment] 2016-09-30 13:41
@mellissatort This is a more significant client change and will require an app update. I would suggest trying a different template until I have a chance to work on this.

**Comment by mellissatort** [comment] 2016-09-30 21:12
@matthewtsmith we have chosen a different template to work around this issue until client change can be completed.

**Comment by matthewtsmith** [comment] 2016-10-05 13:34
Duplicate of https://github.com/apptreesoftware/revolution/issues/3

**Comment by matthewtsmith** [comment] 2016-10-13 13:36
Fixed in 5.4.4 iOS and 5.4.5 Android

**Closed** 2016-10-13 13:35 UTC
Labels: Android, bug, iOS
